name: Build release mode

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: master

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build ReleaseFast
        run: |
          zig version
          make build-optimize
          echo "Binary size:"
          du -h ./zig-out/bin/ziggy-starkdust

      - name: Generate artifact name
        id: artifact-name
        run: |
          export COMMIT_HASH=$(git rev-parse --short HEAD)
          export CURRENT_DATE=$(date +"%Y%m%d")
          export ARTIFACT_NAME="ziggy-starkdust_${CURRENT_DATE}_${COMMIT_HASH}_$(uname -m)"
          echo "::set-output name=artifact_name::$ARTIFACT_NAME"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.artifact-name.outputs.artifact_name }}
          path: ./zig-out
